version: "3.1"
services:
  # For bot messenger
  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: hiuFinale2k24
      MYSQL_PASSWORD: hiuFinale2k24
      MYSQL_DATABASE: hiu-finale-db
      MYSQL_USER: hiu_finale
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    ports:
      - 86:80
    environment:
      MYSQL_ROOT_PASSWORD: hiuFinale2k24
      MYSQL_PASSWORD: hiuFinale2k24
      MYSQL_DATABASE: hiu-finale-db
      MYSQL_USER: hiu_finale
      PMA_HOST: mysql
    
volumes:
  mysql: ~